get-dependencies:
	-[ ! -f mhegtools/compiler.jar ] && mkdir -p mheg-tools && wget  -O mheg-tools/compiler.jar https://master.dl.sourceforge.net/project/mhegplus/MhegPlus.Compiler-1.0.1a.jar
	-[ ! -f mhegtools/player.jar ] && mkdir -p mheg-tools && wget  -O mheg-tools/player.jar https://master.dl.sourceforge.net/project/mhegplus/MhegPlus.MhegPlayer-1.0.1a.jar

.PHONY: get-dependencies
